### ISSUE TITLE
Mobile: Banner navigation slick dots was displayed outside the banner image

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rare-Parts#112]
iTouch - portrait

![image](https://cloud.githubusercontent.com/assets/12791909/12227325/e7eb9564-b865-11e5-8618-001a3207f576.png)

**Comment by ermatitan** [comment]
Not fix. The navigation dots no longer displayed or cannot be seen.

**Comment by ermatitan** [comment]
still not fix

**Comment by suniltitan** [comment]
Slick dots and find more button over lapped in i touch portrait view,that's why i am removed slick dots from i touch portrait view.
