### ISSUE TITLE
Header - Menu navigation - There is no option on how to edit/replace menu icons. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rare-Parts#125]
![image](https://cloud.githubusercontent.com/assets/12791909/12470300/f4d90e4e-c02d-11e5-8765-65bc8df27740.png)

**Comment by suniltitan** [comment]
It is out of scope,i need to discuss with salman for approval

**Comment by suniltitan** [comment]
Hi Erma,
This one is still under discussion between Salman and Bernard. I am waiting for the final outcome, so to fix this one out. Once i will get the update from Salman, i will fix this up accordingly.
In the meantime others bugs have been fixed.

**Comment by suniltitan** [comment]
You can add the menu icons in options page

![menu icon screen shot](https://cloud.githubusercontent.com/assets/14212899/12750454/71770466-c9dd-11e5-94c5-6c1d8d4f84d1.png)
