### ISSUE TITLE
Our Parts - Inconsistent product thumbnails size

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rare-Parts#131]
![image](https://cloud.githubusercontent.com/assets/12791909/12471147/d0ec42f0-c035-11e5-9fa7-4777fd2f94b4.png)

**Comment by suniltitan** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/14212899/12605580/2fbc58aa-c4ec-11e5-89c1-4aa73b845b6c.png)

**Comment by suniltitan** [comment]
Please add the above dimensional image.If you add below 370*252 dimensional image, design will be Inconsistent.
