### ISSUE TITLE
Home - social feeds: The social feed section doesn't occupy the entire width of the page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Rare-Parts#79]
![image](https://cloud.githubusercontent.com/assets/11186313/12111381/c00d9488-b3cf-11e5-9f76-350fc69723d7.png)

**Comment by ermatitan** [comment]
as per Carin comment: "still looking for solutions
![image](https://cloud.githubusercontent.com/assets/12791909/12471220/76d60016-c036-11e5-9fae-aa1c8f2b4a75.png)
