### ISSUE TITLE
Homepage : Testimonial content acf not displayed on the front-end.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rare-Parts#90]
![image](https://cloud.githubusercontent.com/assets/12791909/12161180/e2ca2266-b52d-11e5-92d3-32313e0d4a9e.png)

**Comment by suniltitan** [comment]
For Carin instructions we are removed the testimonial content

**Comment by ermatitan** [comment]
Testimonial content ACF should also be removed in the backend:
![image](https://cloud.githubusercontent.com/assets/12791909/12469508/534b999e-c027-11e5-91ae-d288927bc711.png)
